//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BManEntities : DbContext
    {
        public BManEntities()
            : base("name=BManEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<building> buildings { get; set; }
        public DbSet<colony> colonys { get; set; }
        public DbSet<flat> flats { get; set; }
        public DbSet<currentBill> currentBills { get; set; }
        public DbSet<flatNumber> flatNumbers { get; set; }
        public DbSet<flatRent> flatRents { get; set; }
        public DbSet<wasaBill> wasaBills { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<subcription> subcriptions { get; set; }
        public DbSet<subUser> subUsers { get; set; }
        public DbSet<user> users { get; set; }
    }
}
