//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class colony
    {
        public colony()
        {
            this.flats = new HashSet<flat>();
        }
    
        public int id { get; set; }
        public int colonyCode { get; set; }
        public string colonyName { get; set; }
        public int buildingCode { get; set; }
        public string buildingName { get; set; }
        public string username { get; set; }
    
        public virtual ICollection<flat> flats { get; set; }
    }
}
