//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string empid { get; set; }
        public string joinDate { get; set; }
        public string resignDate { get; set; }
        public string salary { get; set; }
        public string mobile { get; set; }
        public string usertype { get; set; }
    }
}
